import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

//my fist questing is why did you not create the layout of the different sections  in this file?
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* for example the menu secton <menu/>
      then <left section/>
      and finally <main view/> */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
